<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>bfc8bdbf-0014-49e5-99bc-7e7a89ddec47</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Datamesh.API\Datamesh.API.csproj" />
    <ProjectReference Include="..\Datamesh.UI.ApiService\Datamesh.UI.ApiService.csproj" />
    <ProjectReference Include="..\Datamesh.UI.Web\Datamesh.UI.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="8.1.0" />
  </ItemGroup>

</Project>
